# Generated by Django 3.0.4 on 2020-03-08 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Copo',
        ),
    ]
